#ifndef SMARTNODE_COMMONHEAD_H
#define SMARTNODE_COMMONHEAD_H
#include <cstdio>
#include <cstdlib>
#include <sys/types.h>
#include <unistd.h>
#include <pthread.h>
#include <fcntl.h>
#include <sys/stat.h>
#include <sys/socket.h>
#include <pthread.h>
#include <sys/ioctl.h>
#include <sys/time.h>
#include <netdb.h>
#include <net/if.h>
#include <ifaddrs.h>
#include <arpa/inet.h>
#include <strings.h>
#include <errno.h>
#include <sys/wait.h>
#include <algorithm>
#include <cstdarg>
#include <cstring>
#include <ctype.h>
#endif //SMARTNODE_COMMONHEAD_H
